apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-pod
  labels:
    name: web
spec:
  containers:
  - name: hello-kube
    image: fhsinchy/hello-kube
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
